{
 "title": "Cars accesses",
 "time": { "from": "2024-10-02T16:43:03.474Z", "to": "2024-10-02T16:45:10.530Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Statistics on cars",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_project\")\n            |> range(start: 0) \n            |> filter(fn: (r) => r._measurement == \"car_plates\")\n            |> filter(fn: (r) => r._field == \"value\")\n            "
    }
   ]
  },
  {
   "title": "Last rejected plate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_project\")\n            |> range(start: 0) \n            |> filter(fn: (r) => r._measurement == \"car_plates\")\n            |> filter(fn: (r) => r._field == \"value\")\n            |> filter(fn: (r) => r._value == -1)\n            |> group(columns: [\"host\"], mode:\"by\")\n            |> last()"
    }
   ]
  },
  {
   "title": "Last allowed access",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_project\")\n            |> range(start: 0) \n            |> filter(fn: (r) => r._measurement == \"car_plates\")\n            |> filter(fn: (r) => r._field == \"value\")\n            |> filter(fn: (r) => r._value == 1)\n            |> group(columns: [\"value\"], mode:\"by\")\n            |> last()"
    }
   ]
  },
  {
   "title": "Today accesses",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot_project\")\n            |> range(start: -1d) \n            |> filter(fn: (r) => r._field == \"value\")\n           "
    }
   ]
  }
 ]
}